### ISSUE TITLE
Ability to set up different branch to use for each plugin

### ISSUE THREAD

**Issue by bzbug** [erf/vis-plug#5]
# Problem

```lua
local plugins = {
	['https://github.com/u/vis-one.git'] = { 'init', 'var1' },
	['https://github.com/u/vis-two.git'] = 'init'
}
local plug = require('plugins/vis-plug')
plug.init(plugins)
```

`vis-two` has `experimental` branch. I can install the plugin, then switch to the branch manually and then enjoy, but it's not always convenient:

1. `plug` should manage this kind of thing, it's the whole point of it.
2. The configuration is not easily portable. I'm thinking, with `plug` the matter of setting up one's whole plugin enviromnent should be a matter of requiring `plug` with proper settings and executing install command.

# Desired behaviour

```lua
local plugins = {
	['https://github.com/u/vis-one.git']   = { file = 'init', var = 'var1' },
	['https://github.com/u/vis-two.git']   = { file = 'init', branch = 'experimental' },
	['https://github.com/u/vis-three.git'] = 'vis-three'
}
local plug = require('plugins/vis-plug')
plug.init(plugins)
```

`plug-install` and `plug-update` should also switch to the branch set up in settings.

**Comment by erf** [comment]
I'm not sure if experimental branches in vis plugins are a very normal use case, and i rather keep this minimal.

But feel free to experiment in your own fork, maybe i'll consider a PR, if it looks sound.

Out of curiosity.. Are you using `vis-plug` yourself now? And do you have experimental branches for vis plugins you use?

**Comment by Yodzorah** [comment]
I'm using `vis-plug` and the recent features you added (except for themes support, but I'm planning to get to it, was kind of busy with plugins). And I do have a fork of `vis-commentary`, where I want to have a branch with new features, so that I could keep `master` updated with `master` from the original, which would allow me to both introduce new features to the original _and_ have them all already implemented on experimental branch so that I could use those features right off.

**Comment by erf** [comment]
Ok, i might add this. I like the table with keys.

**Comment by Yodzorah** [comment]
\+ on second thought, it might be better to switch to specified branches on `init`. Consider this scenario:

1. A plugin is already installed, default branch used (no branch specified in settings for `plug`).
2. The user changes settings for `plug`, specifying new branch for the plugin, but does not execute `plug-update`, because, technically, it would mean he wants to update the plugin, not the settings for it.
3. The user re-opens `vis`, but the plugin uses the old branch. Confusion.

So, maybe `plug-install` and `plug-update` should only do what they are meant to do - install and update, and switching will always happen on `init`.

**Comment by erf** [comment]
I pushed a few commits now - can you check it out? I set branch on `vis-install` and `vis-update`, it makes sense to me as it works as it did before. That is you need to explicit call `vis-install` or `vis-update` or `install_on_init` to install or update plugins. I'm a bit tired now, so maybe i messed something up. Will try to clean up the code later.

**Comment by Yodzorah** [comment]
Works nicely for me <3

Although, I'm still not sure it's a good thing to switch branches on `install` or `update` commands or even when `install_on_init` is on. This has nothing to do with installation, it's very unexpected behaviour from user's point of view. I'd expect something like that to change when I change my configuration file and re-start `vis`.

... but if you _really_ think it's a good idea, it's worth a mention in README.

**Comment by erf** [comment]
I think my logic was that, if you now add a new plugin with a url to the configuration, nothing happens until you do a install, either via `install_on_init` or explicitly calling `vis_install`, so why should the branch change without an explicit command? If you already have done a `pull` on that branch, it is a "light" call, but you might not have done a `pull` before, so now you both have to do a `pull` and `checkout` and that would hang the editor - and that's why i think it's better to be explicit about it. I can mention it in the docs, i did previously but i can add it back in.

**Comment by Yodzorah** [comment]
The thing is - you describe the `git` logic behing `plug`, not the _plugin_ logic. And, by doing that, you require the user think about the _implementation_ of `plug` instead of the convenient abstractions it provides.

And now I realized your approach has another issue - switching to a branch is impossible to make without updating all plugins. I mean, it's not OK that the _affected_ plugin is updated every time the user switches to a branch (the user only wanted to switch to a branch, not _update_; what if something's broken in later commits or the plugin became incompatible with the other plugins the user has?), let alone all plugins. Imagine updating 10 plugins just to switch to a branch on a tiny one. You said you want to keep `plug` small, so I'm not sure what's better in this situation: leave it like that or add some way to update separate plugins instead of the whole bunch. Maybe add a separate command just for switching branches?

**Comment by erf** [comment]
I added a comment regarding `vis-install` and `vis-update` in more abstract terms in addition to what it actually do, but this plugin is for `vis` an "expert level" text editor, that is for developers who has the ability to, and should read the source code.

Regarding your second comment, `vis-plug` was supposed to be just a light weight "installer" almost for vis plugins, NOT a git command tool. How often do you plan on switching branches of your vis plugin? I did not think of that as a use case. I could perhaps add a `commit` option to which would checkout a specific commit.

BTW, i appreciate your feedback, but when you make issues / comments, please refrain from saying things like "it's the whole point of it." or "it's very unexpected behaviour from user's point of view.", or "it's not OK", as you are kind of generalising or sounding demanding. I made this for myself mostly for myself for fun and experimentation, and i doubt many people use it. Humble suggestions are fine. Thanks.

**Comment by erf** [comment]
You can now set a `commit` option, and if you set `install_on_init` to `true` it will change branch/commit on startup.

**Comment by Yodzorah** [comment]
> BTW, i appreciate your feedback, but when you make issues / comments, please refrain from saying things like "it's the whole point of it." or "it's very unexpected behaviour from user's point of view.", or "it's not OK", as you are kind of generalising or sounding demanding. I made this for myself mostly for myself for fun and experimentation, and i doubt many people use it. Humble suggestions are fine. Thanks.

For future issues: I suspected it may look like it for some people, but I honestly don't know how to explain things like that from my point of view without... explaining them honestly. For example, how one describes one's confusion about a plugin not doing what it claims it does? It may look like nothing, but user's confusion often indicates a subtle problem in the product, e. g. it behaves in unexpected ways or only half-automates the task it's made for. So, I thought, it may be best to report that experience as I would report a bug and let the maintainers decide whether the problem is in the product or the user. It's not like I'm knocking on your door demanging to do this and that, I give you feedback, but _you_ decide whether it's useful or not and what to do with it. Best thing I can do in a discussion, imo, is to argue back as best as I can to provide most valid points I can muster, and then let the maintainer decide if the resulting points are objectively valid enough to do something. Thought thrives on conflict and all that. All the while I don't seriously _think_ the maintainer owes me something. So, it may _look_ like there's some emotion or indignation or whatever behind such phrases, because not all people talk like that, but in fact it's just an attempt to describe the problem better.

I honestly don't know how to do "humble suggestions" without refraining from arguing back. So, if what I described is still not OK, let me know and I'll switch from useful to humble.

**Comment by erf** [comment]
I have not really claimed that "plug" does anything (more than i've said in the README), but you seem to think that there are expectations from multiple "users" that this should do certain things. You, have made up these expectations. And the "product" is not commercial product, but open source and free, built for free, to a niche audience, so although i'd appreciate feedback or contributions, you should be aware how you phrase yourself. That is, talk from your own point of view, not "users", and not make up expectations that may not be there from the creators point of view, but rather be humble, or you'll just rub people the wrong way.

**Comment by erf** [comment]
BTW, i have probably done these types of things myself alot, but you know, you learn.

**Comment by erf** [comment]
Also, when posting issues you put a cartain amount of pressure on the maintainer, so make sure these are valid pain points, and not something that might be useful in the future..

**Comment by erf** [comment]
Maybe i overreacted the other day with some of these comments and put too much interpretation in some of the words you used. In that case, i'm sorry. I appreciate the feedback, and i think some nice updates were made because of it.

**Comment by erf** [comment]
@bzbug Sorry for the previous "noise" (i removed some comments), i guess was in weird headspace. I'd appreciate some help with improving this issue, and create a good user experience. I made a few changes, but it might be still improved on.

I'd like to default to the "default" `master` / `main` branch, but from what i gather it is not always named that, nor is the `origin`, so i'm thinking if the user does change the to another branch, it should always be set explicit.

I also would avoid doing a `checkout` if already on the correct branch to avoid slow startup times ( this only applies if `install_on_init` is `true`).

I'm also considering adding a `plug-checkout` command.

My `git` knowledge is a bit limited, so any help/tips here would be useful.

**Comment by erf** [comment]
Implemented `plug-checkout` command via 9b6b0dc
